### ISSUE TITLE
Designtime Exception when mixing .NET Standard project libraries with WPF .NET Framework application

### ISSUE THREAD

**Issue by olitee** [lbugnion/mvvmlight#41]
I've discovered a potential bug when mixing .NET Standard library projects with a .NET Framework WPF project.

## Scenario

Two projects:
+ .NET Standard class library project (targeting .Net Standard 2.0)
    - No other dependencies or implementations. Just an empty project.
+ WPF Front end project (targeting .NET 4.7)
    - References the above .NET standard project
    - Nuget package management format set to 'PackageReference'
    - References nuget package: MvvmLightLibs

## Symptoms

The app runs as expected at runtime, but during design time a FileLoadException is thrown whenever `ViewModelBase.IsInDesignModeStatic` is called:

![image](https://user-images.githubusercontent.com/1835892/42807626-36c40984-89a9-11e8-9724-d980772d644d.png)

NOTE: this exception does not show up immediately on the first build, but usually kicks in once VS has been restarted - or 'Disable Project Code' is toggled in the XAML editor.

## Source of the error
The exception is being thrown within the `GetCurrentPlatform()` of the [Designer Library (Line 47)](https://github.com/lbugnion/mvvmlight/blob/master/GalaSoft.MvvmLight/GalaSoft.MvvmLight%20(PCL)/Helpers/DesignerPlatformLibrary.cs#L47)

## Steps to reproduce
[MvvmLightDesignModeBug.zip](https://github.com/lbugnion/mvvmlight/files/2201045/MvvmLightDesignModeBug.zip)

This simple project implements the bare minimum to reproduce the error. Note that on first build the designtime view may appear to work. Try toggling the `Disable Project Code` button on and off: 
![image](https://user-images.githubusercontent.com/1835892/42809138-c9f5c0e6-89ac-11e8-8662-c4b0acc0be69.png)

## Notes
This exception appears whether using the MvvmLightLibs or MvvmLightLibsStd10 packages.

Removing the WPF project's reference to the .NET standard class library will fix this error.

## Potential Fix
Wrapping the calls to [Type.GetType() in the DesignerLibrary](https://github.com/lbugnion/mvvmlight/blob/master/GalaSoft.MvvmLight/GalaSoft.MvvmLight%20(PCL)/Helpers/DesignerPlatformLibrary.cs#L47) with a try-catch so that failures here fall through.

UPDATE: Pull request #42 submitted.

**Comment by TheMiller2015** [comment]
Hello, thanks for your investigations. I just hit the same error and confirm this behaviour. That stole me two days. Would you be so kind and tell me, how I can modify the source of mvvmlight like you suggested? I haven't done this before. And, @lbugnion why isn't that pull request merged? I really appreciate your work, but this is a bug that should be fixed as soon as possible. Thanks to both of you for yours works and sharings.
btw: my setup is a solution with many projects. Most of the dependencies come from my own nuget-feed, but the Logic is only an assembly of that solution (it is a .netstandard2.0 assembly) and the UI-Project is .net 4.6.2, referencing the logic.dll. The case is, that I also have xamarin(forms) projects that have to reference the logic. So the logic has to be / should be .netstandard.

**Comment by Nullstr1ng** [comment]
I was trying to make an issue and good thing I found this one. The issue still exists in 5.4.1.1

I took the DesignerLibrary and added a try_catch block for Silverlight and that worked well. I actually made a git repo with this one that can be found here
https://github.com/Nullstr1ng/MVVMLightIssueInNETStandard

as well as the modification I made
https://github.com/Nullstr1ng/MVVMLightIssueInNETStandard/blob/251af789a8bc819ba1acd906dfd000cad22ecf90/BugInMvvmForWPF.Lib/Helpers/DesignerLibrary.cs#L46

**Comment by TheMiller2015** [comment]
Hello again. I know, that you are busy. But I'm begging you... please.. can you publish a nuget package with that current fix? Since the purpose is to have one codebase for all platforms, it is an usual scenario to mix .netstandard and wpf. You would make the crowd very happy, I think. And I'm also relying on the ability to use design time data. Compiling and executing for creating UI is a very slow process. I would be happy, when you give me/us a small feedback. Thanks in advance - many, many times.

**Comment by Nullstr1ng** [comment]
I have a fix if you like

**Comment by TheMiller2015** [comment]
In the meantime this is the way to go, I thank. I'm very thankful and just checked out your repo. It's just building and referencing it from logic and UI project, right?

**Comment by TheMiller2015** [comment]
Sorry, I don't get your solution to run, @Nullstr1ng . I checked out the branch "hacked_designerlibrary_class" and build your solution. But how to implement your fix into my solution? Can leave leave some explaining words here, please? ;) thanks.

**Comment by olitee** [comment]
If you'd prefer to stick with the published packages for now, and add in a workaround, I'm currently using this helper utility in my original app (the app I filed this issue from):

```c#
public static class DesignTime
    {
        private static bool? _isInDesignMode = null;
        public static bool IsInDesignMode => _isInDesignMode ?? (_isInDesignMode = GetIsInDesignMode()).Value;

        private static bool GetIsInDesignMode()
        {
            var isInDesignMode = (bool?)null;
            var prop = DesignerProperties.IsInDesignModeProperty;
            isInDesignMode
                = (bool)DependencyPropertyDescriptor
                    .FromProperty(prop, typeof(FrameworkElement))
                    .Metadata.DefaultValue;

            // Just to be sure
            if (!isInDesignMode.Value
                && Process.GetCurrentProcess().ProcessName.StartsWith("devenv", StringComparison.Ordinal))
            {
                isInDesignMode = true;
            }

            return isInDesignMode ?? false;
        }
    }
```

How you use it is up to you - but I've just created my own viewmodel baseclass that inherits from MVVMLight's `ViewModelBase` class, and then just overrides this logic. I'm happy with this workaround, as I often create my own viewmodel baseclasss in my projects anyway, so this feels fairly light in terms of a hack.

@lbugnion I'm sure is a busy man :)

Also, don't forget the fix in the MVVMLight source is very simple, and detailed in PR #42 in case you just want to pull the source, and fix it yourself.

**Comment by TheMiller2015** [comment]
Yes well done. I used the master branch of the mvvmlight sources, since your static class "DesignTime" won't compile in my .netstandard2.0 project (compiler can't find "DesignerProperties"). So I compiled the master branch and also added "System.Windows.Interactivity" and "...mvvmlight.Platform" as reference. I initially forgot these two extra references in the UI project and couldn't compile. Shame on me. As a result, everthing is working fine and I want to say "thanks@all" for your quick help.
